### ISSUE TITLE
tracking bug for notebooks migration + CI/CD

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/python-docs-samples#3763]
Closing 3 issues in favor of tracking them all in one spot - during the 2020 Python Docs Samples spring cleaning we discussed the status of these and the migration of the notebooks to a different location is still in progress. When it is complete, they will be removed from this repo

- [ ] https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2461
- [ ] https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2381
- [ ] https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2380

**Comment by kweinmeister** [comment]
AFAIK there are no plans to add notebook support to this repo. Also, this covers the previous AutoML service before it was included in Vertex AI.
